ALTER TABLE user
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE role
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE user_role
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

